### ISSUE TITLE
QAP无法启动工程

### ISSUE THREAD

**Issue by zhuofannuo** [weex-nuke/discuss#18]
node.js版本v10.12.0
qap版本v3.1.15

升级老版本后qap-cli后出现工程启动错误问题
qap clear后执行qap install latest提示错误信息：
[core-module] 本地尚未安装 fie-toolkit-nuke ,正在执行自动安装...
\ [0/1] Installing @ali/0-client-core@^1.1.13[@ali/0-client-core@^1.1.13] optional install error: Error: GET http://registry.npm.taobao.org/@ali%2F0-client-core response 404 status
    at get (C:\Users\zhiqim\AppData\Roaming\npm\node_modules\qap-cli\node_modules\_npminstall@3.12.0@npminstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\zhiqim\AppData\Roaming\npm\node_modules\qap-cli\node_modules\_co@4.6.0@co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
× Install fail! Error: EBUSY: resource busy or locked, symlink 'C:\Users\zhiqim\.fie\node_modules\_get-assigned-identifiers@1.2.0@get-assigned-identifiers'
 -> 'C:\Users\zhiqim\.fie\node_modules\_undeclared-identifiers@1.1.2@undeclared-identifiers\node_modules\get-assigned-identifiers'
Error: EBUSY: resource busy or locked, symlink 'C:\Users\zhiqim\.fie\node_modules\_get-assigned-identifiers@1.2.0@get-assigned-identifiers' -> 'C:\Users\zhiqim\.fie\node_modules\_undeclared-identifiers@1.1.2@undeclared-identifiers\node_modules\get-assigned-identifiers'
npminstall version: 3.12.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\zhiqim\AppData\Roaming\npm\node_modules\qap-cli\node_modules\_npminstall@3.12.0@npminstall\bin\install.js fie-toolkit-nuke@latest --cwd=C:\Users\zhiqim\.fie --registry=http://registry.npm.taobao.org/ --china --stdio=inherit
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
[core-error] 安装 fie-toolkit-nuke@latest 出错,请确认网络是否正常及包名是否输入正确

qap debug命令提示以下错误信息：
[core-error] 运行插件或套件时出现了错误, 未找到 lodash 模块! 正在尝试自动修复...
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 118ms(network 113ms), speed 281.01kB/s, json 1(31.75kB), tarball 0B)
[core-error] 已将 lodash 模块安装至 C:\Users\zhiqim\.fie ,自动修复成功,请重新运行命令!
[core-error] 若重新运行仍然出现问题，请在命令前面加上：DEBUG=core-error 来获取详细错误堆栈

再次执行qap debug命令：
[core-error] 运行插件或套件时出现了错误, 未找到 lodash 模块! 正在尝试自动修复...
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 118ms(network 113ms), speed 281.01kB/s, json 1(31.75kB), tarball 0B)
[core-error] 已将 lodash 模块安装至 C:\Users\zhiqim\.fie ,自动修复成功,请重新运行命令!
[core-error] 若重新运行仍然出现问题，请在命令前面加上：DEBUG=core-error 来获取详细错误堆栈

执行命令qap create my-project：
创建工程： my-object
[core-commands] 当前目录下已存在文件,继续执行初始化会覆盖已存在的同名文件? 确认需要继续执行初始化,请输入(y) y
提示后就没反应了qap init也不行和qap create一样

**Comment by fattydevelop** [comment]
参考：https://github.com/npm/npm/issues/13461#issuecomment-282556281

文件lock大部分情况是有其他软件在对文件进行读写，建议关闭防火墙或者杀毒软件后再执行 `qap clear && qap install latest`
