### ISSUE TITLE
新版qap.config下无法添加自定义babel控件

### ISSUE THREAD

**Issue by notcold** [weex-nuke/discuss#19]
旧版本下有通过一些自定义的babel插件来优化包大小，在新项目下不行了导致包的体积急速上升，
麻烦后面加一下babel插件的配置

**Comment by fattydevelop** [comment]
双11后会增加一个babelrc开关，开放自定义入口。
本次发布功能包括：

- 全局babelrc开放
- babelInclude 设置
- pagemaster设置
- 装饰器支持
- 增加tempalte命令


具体使用方式可以在qap.config.js 的toolkitConfig字段中增加babelrc:true 的设置

![image](https://user-images.githubusercontent.com/3349721/49125918-bbb9da80-f2fc-11e8-92d7-c20e7175249b.png)

举例来说：如果我想在项目中增加`babel-plugin-transform-remove-console`，需要进行以下几步操作。
- 在根目录增加一个`.babelrc`文件，该文件的解释和格式与babel文档中一致。
- 在`package.json`中增加`babel-plugin-transform-remove-console`，并安装。
- 在.babelrc文件中增加所需babel配置如下：
 ```
 {
   "plugins": ["transform-remove-console"]
 }
 ```
