### ISSUE TITLE
ios下 TextInput maxLength失效

### ISSUE THREAD

**Issue by xiaoqiang730730** [weex-nuke/discuss#9]
```jsx
<TextInput 
  style={styles.pointMoreInput}
  value={points[4]}
  onInput={(e)=> {this.changePoints(e.value, 4)}}
  maxLength='6'
  ></TextInput>
```
![qq 20170213161850](https://cloud.githubusercontent.com/assets/8445916/22875828/af68dfe8-f208-11e6-9799-2367ee72009a.png)

**Comment by fattydevelop** [comment]
maxLength的类型是number,`maxLength={6}`

**Comment by xiaoqiang730730** [comment]
我这边确实是‘6’, 但是为啥安卓机又有效啊，

**Comment by fattydevelop** [comment]
ios和android native端的兼容性实现有差别，推荐还是使用我们指定的的类型传参
